LOCAL_PATH := $(call my-dir)

CORE_DIR := $(LOCAL_PATH)/..

ARCH_IS_LINUX = 1
ARCH_IS_MACOSX = 0
ARCH_IS_WINDOWS = 0
HAVE_SYS_PARAM_H = 1
FORCE_GLES = 1
FASTMATH = 1
UNROLL_LOOPS = 1
HAVE_FSEEKO = 0
USE_RTHREADS = 0

FLAGS :=

include $(CORE_DIR)/Makefile.common

FLAGS += -DANDROID

include $(CLEAR_VARS)
LOCAL_MODULE       := retro
LOCAL_SRC_FILES    := $(SOURCES_CXX) $(SOURCES_C) $(SOURCES_S)
LOCAL_C_INCLUDES   := $(INCLUDE_DIRS)
LOCAL_CFLAGS       := -std=gnu11 $(COMMON_FLAGS)
LOCAL_CPPFLAGS     := -std=gnu++11 $(COMMON_FLAGS)
LOCAL_LDFLAGS      := -Wl,-version-script=$(CORE_DIR)/link.T
LOCAL_LDLIBS       := -lGLESv3
LOCAL_CPP_FEATURES := exceptions rtti
LOCAL_ARM_MODE     := arm

ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
  LOCAL_ARM_NEON := true
endif

include $(BUILD_SHARED_LIBRARY)
