# Uncomment the next line to define a global platform for your project
# platform :ios, '9.3'

target 'uoyabause' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'

  # Pods for uoyabause

  target 'uoyabauseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uoyabauseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
