.TH YABAUSE 1 "October 20, 2008" "yabause-0.9.7"
.SH NAME
yabause \- Yet Another Buggy And Uncomplete Saturn Emulator
.SH SYNOPSIS
.B yabause
.SH DESCRIPTION
\fBYabause\fP is a Sega Saturn emulator. \fBYabause\fP needs either a bios file, a game or a binary to run.
Games can be loaded from a real cd device or from dump files.
.SH FILES
.TP
\fB<BIOS>\fR
A Saturn ROM BIOS image.
.SH AUTHORS
Copyright (c) 2002-2008 Yabause Team

Web:	http://yabause.org

Please don't ask for roms, bios files or any other
copyrighted stuff.
.SH COPYRIGHT
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as 
published by the Free Software Foundation; either version 2 of 
the License, or (at your option) any later version.

This program is distributed in the hope that it will be
useful,but WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public
License along with this program; if not, write to the Free
Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301  USA

See the GNU General Public License details in COPYING.
